name: "THN CLI: CI"

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "CI v2"
    runs-on: ubuntu-latest

    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TERM: xterm-256color
      COLUMNS: "120"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install package and development dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: "Run pytest"
        run: pytest -q
